from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain.schema.output_parser import StrOutputParser
from dotenv import load_dotenv

load_dotenv()

def output_response(groq_api_key,user_input="Vk kohli"):
    
    llm=ChatGroq(
        model="mixtral-8x7b-32768",
        temperature=0.5,
        api_key=groq_api_key
    )

    
    """Provide the response generated by the model for the particular celebrity in json format"""

    first_template= """You are a assistant of {name} who is celebity and you know in and out of him/her.

                    Provide result in json format with key as:
                    description(2-3 lines),
                    DOB, 
                    MaritalStatus, 
                    Occupation details, 
                    Qualification detail,
                    Achivements. and many more if required
                    
                    If he/she is not a celebrity member according to you then provide the answer with description as "not a celebrity" and all other value as null. No preamble.
                    """
    first_prompt=ChatPromptTemplate.from_template(template=first_template)

    chain1=(
    first_prompt | llm | StrOutputParser()
    )
    response=chain1.invoke({'name':user_input})
    return response

